CREATE TABLE `test`.`USERS3` (
  `USER_ID` INT(8) NOT NULL,
  `USER_NAME` VARCHAR(25) NOT NULL AUTO_INCREMENT,
  `USER_AGE` INT(11) NOT NULL,
  `U_ISADMIN` BIT(1) NOT NULL,
  `U_CREATEDATE` TIMESTAMP NOT NULL,
  PRIMARY KEY (`USER_ID`));